# Generated by Django 5.0.2 on 2024-02-29 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_expiration_date_product_ends_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='default_product.png', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('service', 'Service'), ('music', 'Music'), ('video', 'Video'), ('blockchain', 'Blockchain'), ('ai', 'Artificial Intelligence'), ('iot', 'Internet of Things'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='AuthorLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Author Likes',
                'db_table': 'author_likes',
                'unique_together': {('author', 'created_at')},
            },
        ),
    ]
